### ISSUE TITLE
Bug deploy action

### ISSUE THREAD

**Issue by pierreleripoll** [EPFL-ENAC/epfl-enac-deploy-action#12]
Hello ! When trying to deploy (with resslab-hub-test) I have an error https://github.com/RESSLab-Team/resslab-hub/actions/runs/8159633888/job/22304380566

2024-03-05 17:27:06 fatal: [resslab-hub-test.epfl.ch]: FAILED! => {"changed": false, "msg": "Configuration error - kwargs_from_env() got an unexpected keyword argument 'ssl_version'"}

 Apparently it has something to do with docker compose, @guilbep  says it's because we use "docker-compose" instead of "docker compose"
 
 https://stackoverflow.com/a/77651191

**Comment by nicdub** [comment]
It seems @guilbep is right, I was able to deploy resslab-hub-test with enacit-ansible's app-deploy after I fixed it to use the new docker compose (see this [pull request](https://github.com/EPFL-ENAC/enacit-ansible/pull/172)).
