### ISSUE TITLE
Security: isolate enacit-ansible

### ISSUE THREAD

**Issue by sbancal** [EPFL-ENAC/epfl-enac-deploy-action#2]
For security purpose, we must isolate enacit-ansible from the runners trigged by end-user projects _CD_.
Aim: remove __read__ access to repos of collaborators in https://github.com/orgs/epfl-enac/packages/container/enacit-ansible/settings .

**Comment by blueur** [comment]
I didn't get your point...

**Comment by sbancal** [comment]
> I didn't get your point...

We'll discuss this topic
